### ISSUE TITLE
Identify signatures with four haplotypes

### ISSUE THREAD

**Issue by ddelgadillod** [tangerzhang/calc_switchErr#4]
Hello,

I would like to use this software to determine the switch-error in a tetraploid haploid-resolved genome assembly.
I'm trying to run '[Identify signatures between the two haplotypes in ALLHiC assembly](https://github.com/tangerzhang/calc_switchErr#identify-signatures-bewteen-the-two-haplotypes-in-allhic-assembly)',  if on a diploid you suggest comparing haplotype B to haplotype A ( assuming in nucmer A is the reference), How can I compare haplotypes in tetraploid case? Is it necessary to compare every case, when every haplotype is the reference? or always assume A as a reference.

**Comment by tangerzhang** [comment]
Hi @ddelgadillod 
This pipeline was designed to evaluate haplotype-resolved diploid genome assembly and is not applicable to polyploid genomes. You may like to use another pipeline developed in my team to assess the switch errors in a polyploid genome.
https://gitee.com/tanger-lab/polyswitch

**Comment by ddelgadillod** [comment]
Thanks for your answer @tangerzhang 
When I tried to open the URL it is broken, Is this the correct URL?

**Comment by tangerzhang** [comment]
OK, sorry that I forgot to grant you access. Please try it again.

**Comment by phrh** [comment]
Hello,
I tried to use polyswitch to evaluate the switch error in a polyploid. I have HiFi reads, can I used these reads with polyswitch?

I am trying to use these reads, I am running:

`polyswitch -1 m64041_hifi_reads.fasta -2 DC_assembly.ln.fasta -o poly_DC -g 2800000 -r 100`

And I am getting the following output and error

`ln: failed to create symbolic link './reads.fasta': File exists
ln: failed to create symbolic link './genome.fasta': File exists
reads_file : m64041_hifi_reads.fasta
genome_file : DC_assembly.ln.fasta
genome_size : 2800000
reads_number : 100
Traceback (most recent call last):
  File "/datosDC/SError/polyswitch/scripts/filter_qualified_reads.py", line 86, in <module>
    main()
  File "/datosDC/SError/polyswitch/scripts/filter_qualified_reads.py", line 81, in main
    reads_filter_num(file,dic_dict_length_sorted,reads_number,outdir)
  File "/datosDC/SError/polyswitch/scripts/filter_qualified_reads.py", line 23, in reads_filter_num
    with open(output_file, "w") as out_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/datosDC/SError/polyswitch/bin/poly_DC/poly_DC/head_reads.fasta'
cat: head_reads.fasta: No such file or directory


Building a new DB, current time: 03/22/2022 17:49:05
New DB name:   /datosDC/SError/polyswitch/bin/poly_DC/genome
New DB title:  genome.fasta
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /datosDC/SError/polyswitch/bin/poly_DC/genome
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 1142 sequences in 62.7206 seconds.


Warning: [blastn] Number of threads was reduced to 8 to match the number of available CPUs
Warning: [blastn] Query is Empty!
sort: cannot read: valid_window.txt: No such file or directory
cat: valid_ONT_reads.txt: No such file or directory
cat: valid_ONT_reads.txt: No such file or directory
awk: cmd. line:1: error: division by zero attempted`


Do you have any idea what should I do, Should i create a file head_reads.fasta with the fasta headers?
I will appreciate If you can help me

**Comment by eden00Chen** [comment]
@phrh 
I'm sorry that this pipeline is based on ONT ultra long data rather than hifi reads.

And is the output data in the same folder？Please try to keep all the output in the same folder.
this problem occurs mainly because the reads data written in the previous step is not found.

You are using a relative path.Maybe you need to provide a full path when entering the - o parameter，like
 `-o /home/eden/project/poly_DC`

In order to generate this `head_reads.fasta,` you can try this
`filter_qualified_reads.py -f1 reads.fasta -f2 genome.fasta -o $outdir -g $genome_size -r $reads_number`
